class Config:
    EMBEDDING_DIM = 256
    RANDOM_STATE = 42
    TEST_SIZE = 0.3
    N_ESTIMATORS = 300
    MIN_CASES_FOR_ANOMALY_DETECTION = 10
    EMBEDDING_GENERATION_TIMEOUT = 300
    LEAKAGE_CHECK = True
    FEATURE_SELECTION = True
    N_FEATURES = 30
